id,name_en
1,"Anxiety and Stress"
2,"Memory Weakness"
3,"Recurrent Fever"
4,"Chronic Liver Disorder"
5,"Chronic Skin Disease"
6,"Ischemic Heart Disease"
7,"Urinary Stones"
8,"Menstrual Irregularity"
9,"Gastric Ulcer and Hyperacidity"
10,"Intestinal Worm Infestation"
11,"Bronchial Asthma"
12,"Chronic Cough and Bronchitis"
13,"Osteoporosis and Bone Weakness"
14,"Diabetes Mellitus Type 2"
15,Obesity
16,Jaundice
17,"Diarrhea and IBS"
18,"Neuromuscular Weakness"
19,"Anxiety and Stress"
20,"Memory Weakness"
21,"Recurrent Fever"
22,"Chronic Liver Disorder"
23,"Chronic Skin Disease"
24,"Ischemic Heart Disease"
25,"Urinary Stones"
26,"Menstrual Irregularity"
27,"Gastric Ulcer and Hyperacidity"
28,"Intestinal Worm Infestation"
29,"Bronchial Asthma"
30,"Chronic Cough and Bronchitis"
31,"Osteoporosis and Bone Weakness"
32,"Diabetes Mellitus Type 2"
33,Obesity
34,Jaundice
35,"Diarrhea and IBS"
36,"Neuromuscular Weakness"
37,"Anxiety and Stress"
38,"Memory Weakness"
39,"Recurrent Fever"
40,"Chronic Liver Disorder"
41,"Chronic Skin Disease"
42,"Ischemic Heart Disease"
43,"Urinary Stones"
44,"Menstrual Irregularity"
45,"Gastric Ulcer and Hyperacidity"
46,"Intestinal Worm Infestation"
47,"Bronchial Asthma"
48,"Chronic Cough and Bronchitis"
49,"Osteoporosis and Bone Weakness"
50,"Diabetes Mellitus Type 2"
51,Obesity
52,Jaundice
53,"Diarrhea and IBS"
54,"Neuromuscular Weakness"
55,"Anxiety and Stress"
56,"Memory Weakness"
57,"Recurrent Fever"
58,"Chronic Liver Disorder"
59,"Chronic Skin Disease"
60,"Ischemic Heart Disease"
61,"Urinary Stones"
62,"Menstrual Irregularity"
63,"Gastric Ulcer and Hyperacidity"
64,"Intestinal Worm Infestation"
65,"Bronchial Asthma"
66,"Chronic Cough and Bronchitis"
67,"Osteoporosis and Bone Weakness"
68,"Diabetes Mellitus Type 2"
69,Obesity
70,Jaundice
71,"Diarrhea and IBS"
72,"Neuromuscular Weakness"
73,"Anxiety and Stress"
74,"Memory Weakness"
75,"Recurrent Fever"
76,"Chronic Liver Disorder"
77,"Chronic Skin Disease"
78,"Ischemic Heart Disease"
79,"Urinary Stones"
80,"Menstrual Irregularity"
81,"Gastric Ulcer and Hyperacidity"
82,"Intestinal Worm Infestation"
83,"Bronchial Asthma"
84,"Chronic Cough and Bronchitis"
85,"Osteoporosis and Bone Weakness"
86,"Diabetes Mellitus Type 2"
87,Obesity
88,Jaundice
89,"Diarrhea and IBS"
90,"Neuromuscular Weakness"
91,"Anxiety and Stress"
92,"Memory Weakness"
93,"Recurrent Fever"
94,"Chronic Liver Disorder"
95,"Chronic Skin Disease"
96,"Ischemic Heart Disease"
97,"Urinary Stones"
98,"Menstrual Irregularity"
99,"Gastric Ulcer and Hyperacidity"
100,"Intestinal Worm Infestation"
101,"Bronchial Asthma"
102,"Chronic Cough and Bronchitis"
103,"Osteoporosis and Bone Weakness"
104,"Diabetes Mellitus Type 2"
105,Obesity
106,Jaundice
107,"Diarrhea and IBS"
108,"Neuromuscular Weakness"
109,"Anxiety and Stress"
110,"Memory Weakness"
111,"Recurrent Fever"
112,"Chronic Liver Disorder"
113,"Chronic Skin Disease"
114,"Ischemic Heart Disease"
115,"Urinary Stones"
116,"Menstrual Irregularity"
117,"Gastric Ulcer and Hyperacidity"
118,"Intestinal Worm Infestation"
119,"Bronchial Asthma"
120,"Chronic Cough and Bronchitis"
121,"Osteoporosis and Bone Weakness"
122,"Diabetes Mellitus Type 2"
123,Obesity
124,Jaundice
125,"Diarrhea and IBS"
126,"Neuromuscular Weakness"
127,"Anxiety and Stress"
128,"Memory Weakness"
129,"Recurrent Fever"
130,"Chronic Liver Disorder"
131,"Chronic Skin Disease"
132,"Ischemic Heart Disease"
133,"Urinary Stones"
134,"Menstrual Irregularity"
135,"Gastric Ulcer and Hyperacidity"
136,"Intestinal Worm Infestation"
137,"Bronchial Asthma"
138,"Chronic Cough and Bronchitis"
139,"Osteoporosis and Bone Weakness"
140,"Diabetes Mellitus Type 2"
141,Obesity
142,Jaundice
143,"Diarrhea and IBS"
144,"Neuromuscular Weakness"
145,"Homeopathic Bruise and Soft Tissue Injury"
146,"Homeopathic Acute Shock and Fear Reaction"
147,"Homeopathic High Fever with Throbbing Headache"
148,"Homeopathic Dry Painful Cough and Chest Pain"
149,"Homeopathic Joint Sprain and Stiffness"
150,"Homeopathic Indigestion from Overeating and Stimulants"
151,"Homeopathic Acute Grief and Emotional Upset"
152,"Homeopathic Nerve Injury and Shooting Pain"
153,"Homeopathic Local Wound and Slow Healing"
154,"Homeopathic Chronic Sinus Catarrh"
155,"Homeopathic Chronic Skin Eruption and Itching"
156,"Homeopathic Low-grade Fever and Inflammatory Tendency"
